
name: Cover UI

description: Web Developer 

avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

footer-links:
  dribbble:
  email: furkanzerman@gmail.com
  facebook: 
  flickr:
  github: Swindler36
  instagram: codeforevercom
  linkedin:
  pinterest:
  rss: RSS
  twitter: 
  stackoverflow: 
  youtube:
  googleplus: 


disqus:

google_analytics:

baseurl: ""

permalink: /:slugified_categories/:slug

version: v1.2.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :compressed # You might prefer to minify using :compressed


plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate
  - jekyll-archives

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

collections:
  components:
    output: false

encoding: UTF-8

paginate: 10
paginate_path: "/blog/page:num/"

jekyll-archives:
  enabled: all
  layout: page
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'


defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      category: General
  - scope:
      path: ""
      type: "components"
    values:
      layout: "component"